### PR TITLE
Improve XID based on tests with real hardware

### PR DESCRIPTION
**Pull request by JayFoxRox**
This PR implements `XID_GET_CAPABILITIES`; corrects behaviour with interrupt-out; more accurately implements STALL conditions and truncations to actual length. The XID descriptor has also been dumped from a real gamepad.

I used a [small test script to test behaviour of a real gamepad](https://github.com/JayFoxRox/xbox-tools/pull/55) and then [documented my findings on XboxDevWiki](http://xboxdevwiki.net/Xbox_Input_Devices#Protocol).

This fix is intended for Rallisport Challenge, but the following list of games was known to have input issues in XQEMU and should be tested again:

*When testing this PR, don't forget to add `,port=3` to your input option to use "Port 1" on the virtual Xbox. Not all games accept gamepads of controllers plugged into other ports.*

**Working input after this change (most of which previously weren't working):**

- Batman Vengeance
- Big Mutha Truckers 2
- Broken Sword: The Sleeping Dragon
- DRIV3R
- Driver: Parallel Lines
- Ford Mustang: The Legend Lives
- Ford vs. Chevy
- Gladiator: Sword of Vengeance
- Gunvalkyrie
- Hummer Badlands
- Jet Set Radio Future
- Just Cause
- Melbourne Cup Challenge
- Panzer Dragoon Orta
- Peter Jackson's King Kong
- Pulse Racer
- Rallisport Challenge
- Re-Volt
- Rugby League 2
- Second Sight
- Star Wars: Knights of the Old Republic
- Star Wars: Obi-Wan
- Street Racing Syndicate
- TimeSplitters 2
- Tom and Jerry in War of the Whiskers

**Probably errornously mentioned as input issues, not affected by PR:**

- Batman: Rise of Sin Tzu (working menus; Challenge mode: black rectangle covering screen; Story mode: stuck after selecting character. Might have had input issues in menus prior to change?) 
- Maximum Chase (working until title screen, then seems to hang, performance issue or broken graphics updates) 
- Painkiller: Hell Wars (It's another issue - performance) 
- Soldier of Fortune II: Double Helix (black screen after game logo splash screen) 

## Remaining work

This only patches xid.c (which was enough work already and required hours of testing). I hope someone else solves **FIXME PR** or manually moves these changes xid-sdl.c temporarily.

Furthermore the handling out output packets / force feedback was not checked.
Due to the importance of this PR (fixes many games) I do not want to delay it further.
As I'm unfamiliar with the QEMU API (which I find weird), the output-specific code can be considered pseudo-code only.
When moving changes to xid-sdl this definitely has to be reviewed (as that provides an implementation of force feedback for the host).

I originally wanted to test this PR on Linux, comparing a real gamepad to the xid.c using my script.
However, I did not find time for this.
I'm confident this change is mostly correct, and direct comparisons with real hardware can be done later.

### CODE REVIEW

**Comment by JohnGodgames** [comment]
I've tested all of games from list and result are:

- Batman: Rise of Sin Tzu (working at menus, but not ingame or it's another issue)
- Batman Vengeance (working)
- Big Mutha Truckers 2 (working)
- Broken Sword: The Sleeping Dragon (not working)
- Ford Mustang: The Legend Lives (working)
- Ford vs. Chevy (working)
- Gunvalkyrie (working)
- Hummer Badlands (working)
- Just Cause (working)
- Maximum Chase (working until title screen - input lost or it can be another issue)
- Melbourne Cup Challenge (working)
- Painkiller: Hell Wars (It's another issue - performance)
- Panzer Dragoon Orta (working)
- Peter Jackson's King Kong (working)
- Pulse Racer (working)
- Rallisport Challenge (working)
- Re-Volt (not tested yet)
- Rugby League 2 (working)
- Second Sight (working)
- Soldier of Fortune II: Double Helix (working)
- Star Wars: Knights of the Old Republic (working)
- Star Wars: Obi-Wan (working)
- Street Racing Syndicate (working)
- TimeSplitters 2 (partially working)
- Tom and Jerry in War of the Whiskers (working)

**Comment by JayFoxRox** [comment]
I have some of those games and will re-test them, then send a PR upstream - I'll create an issue about xid-sdl seperately.

*(Also great idea to use a diff to color-code them! I'll probably adopt that technique, but use `#` to mark lines without changes)*

**Comment by DarkGabbz** [comment]
Re-Volt is still broken.

**Comment by JohnGodgames** [comment]
Both of these games are working with this PR

```diff 
+ DRIV3R
+ Driver: Parallel Lines

**Comment by JayFoxRox** [comment]
TODO: Test like this on arch with this:

```
 make && x86_64-softmmu/qemu-system-x86_64 ~/Data/Downloads/archlinux-2018.07.01-x86_64.iso -m 512 -machine accel=kvm -fsdev local,security_model=passthrough,id=fsdev0,path=/home/fox/Data/Projects/xqemu-controller-test/ -device virtio-9p-pci,id=fs0,fsdev=fsdev0,mount_tag=h -nic user,model=virtio-net-pci -usb -device usb-xbox-gamepad -device usb-host,vendorid=0x45e,productid=0x289
```

In guest (maybe not entirely correct?):
```
mkdir h
mount -t 9p -o trans=virtio h h
pacman -S python-pip
pip3 install libusb1
```

**Comment by JayFoxRox** [comment]
Broken sword 3 works with real controller, not xid.c. Investigating

```
xid reset
xid handle_control 0x8006 0x100
xid handled by usb_desc_handle_control: 0
xid handle_control 0x5 0x1
xid handled by usb_desc_handle_control: 0
xid handle_control 0x8006 0x200
xid handled by usb_desc_handle_control: 0
xid handle_control 0x9 0x1
xid handled by usb_desc_handle_control: 0
xid handle_control 0xc106 0x4200
xid GET_DESCRIPTOR 0x4200
xid keyboard_event 35 12 0
xid keyboard_event 35 12 0
xid keyboard_event 35 12 0
xid keyboard_event 35 12 0
xid keyboard_event 35 12 1
xid keyboard_event 35 12 0
xid keyboard_event 35 12 0
xid keyboard_event 35 12 0
xid keyboard_event 35 12 0
xid keyboard_event 35 12 1
xid keyboard_event 35 12 0
xid keyboard_event 35 12 1
xid keyboard_event 5 -1 0
xid keyboard_event 3 -1 0
xid keyboard_event 3 -1 1
xid keyboard_event 5 -1 1
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_data 0x69 2 0x20
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_data 0x69 2 0x20
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_data 0x69 2 0x20
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_data 0x69 2 0x20
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_data 0x69 2 0x20
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_data 0x69 2 0x20
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_data 0x69 2 0x20
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_data 0x69 2 0x20
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_data 0x69 2 0x20
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid keyboard_event 35 12 0
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_data 0x69 2 0x20
xid keyboard_event 35 12 0
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_data 0x69 2 0x20
xid keyboard_event 35 12 0
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid keyboard_event 35 12 1
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_data 0x69 2 0x20
xid keyboard_event 35 12 0
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_data 0x69 2 0x20
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid keyboard_event 35 12 1
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid keyboard_event 5 -1 0
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid keyboard_event 3 -1 0
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid keyboard_event 3 -1 1
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid keyboard_event 5 -1 1
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_data 0x69 2 0x20
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_data 0x69 2 0x20
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_data 0x69 2 0x20
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_data 0x69 2 0x20
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
xid handle_control 0xa101 0x100
xid GET_REPORT 0x100
```

**Comment by JohnGodgames** [comment]
Both works.I think that remaining games aren't related to input.
```
    Gladiator: Sword of Vengeance
    Jet Set Radio Future
```

**Comment by JayFoxRox** [comment]
Moved upstream.. finally!

**Pull request closed without merging**
